# Generated by Django 5.1.6 on 2025-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/%Y"),
        ),
    ]
